export const config = {
  ACCESS_TOKEN_URL: "https://github.com/login/oauth/access_token",
  REPOS_URL: "https://api.github.com/repos",
  SEARCH_ISSUES_URL: "https://api.github.com/search/issues",
  SEARCH_REPOSITORIES_URL:
    "https://api.github.com/search/repositories",
  AUTHORIZE_URL: "https://github.com/login/oauth/authorize",
  USER_API_URL: "https://api.github.com/user",
  USER_REPOS_URL: "https://api.github.com/user/repos",
  BSC_POPR_ADDRESS: "0xF45C634B7D2193a6d3D38F94f62cB0A9Ba8DdaE0",
  XDAI_POPR_ADDRESS: "0x39acc10Fc1586f3ba8EC8954e80501e11bCa389C",
  XDAI_TOKEN_ADDRESS: "0x19fc6693132Da591d107202ed65f969EA516FEB8",
  XDAI_TOKEN_TRACKER: "https://blockscout.com/xdai/mainnet/token/",
  NFT_STORAGE_URL: "https://api.nft.storage",
  IPFS_GATEWAY: "https://cloudflare-ipfs.com/ipfs",
  RPC_URL: "https://data-seed-prebsc-2-s3.binance.org:8545/",
  WALLET_CONNECT_BRIDGE: "https://bridge.walletconnect.org",
  WALLET_CONNECT_POLL_INTERVAL: 12000,
  TX_WAIT_BLOCK_COUNT: 3,
  IMAGE_API_URL: '',
};